// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: api/proto/agv.proto

package agv

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DispatchTaskRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TaskId          string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	ContainerId     string                 `protobuf:"bytes,2,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	AgvId           string                 `protobuf:"bytes,3,opt,name=agv_id,json=agvId,proto3" json:"agv_id,omitempty"`
	YardNodeId      string                 `protobuf:"bytes,4,opt,name=yard_node_id,json=yardNodeId,proto3" json:"yard_node_id,omitempty"`
	QuaysideNodeId  string                 `protobuf:"bytes,5,opt,name=quayside_node_id,json=quaysideNodeId,proto3" json:"quayside_node_id,omitempty"`
	Priority        int32                  `protobuf:"varint,6,opt,name=priority,proto3" json:"priority,omitempty"`
	DeadlineUnix    int64                  `protobuf:"varint,7,opt,name=deadline_unix,json=deadlineUnix,proto3" json:"deadline_unix,omitempty"`
	ContainerWeight *ContainerWeightProto  `protobuf:"bytes,8,opt,name=container_weight,json=containerWeight,proto3" json:"container_weight,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DispatchTaskRequest) Reset() {
	*x = DispatchTaskRequest{}
	mi := &file_api_proto_agv_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispatchTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchTaskRequest) ProtoMessage() {}

func (x *DispatchTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agv_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchTaskRequest.ProtoReflect.Descriptor instead.
func (*DispatchTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_agv_proto_rawDescGZIP(), []int{0}
}

func (x *DispatchTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *DispatchTaskRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *DispatchTaskRequest) GetAgvId() string {
	if x != nil {
		return x.AgvId
	}
	return ""
}

func (x *DispatchTaskRequest) GetYardNodeId() string {
	if x != nil {
		return x.YardNodeId
	}
	return ""
}

func (x *DispatchTaskRequest) GetQuaysideNodeId() string {
	if x != nil {
		return x.QuaysideNodeId
	}
	return ""
}

func (x *DispatchTaskRequest) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *DispatchTaskRequest) GetDeadlineUnix() int64 {
	if x != nil {
		return x.DeadlineUnix
	}
	return 0
}

func (x *DispatchTaskRequest) GetContainerWeight() *ContainerWeightProto {
	if x != nil {
		return x.ContainerWeight
	}
	return nil
}

type ContainerWeightProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FrontLeft     float64                `protobuf:"fixed64,1,opt,name=front_left,json=frontLeft,proto3" json:"front_left,omitempty"`
	FrontRight    float64                `protobuf:"fixed64,2,opt,name=front_right,json=frontRight,proto3" json:"front_right,omitempty"`
	RearLeft      float64                `protobuf:"fixed64,3,opt,name=rear_left,json=rearLeft,proto3" json:"rear_left,omitempty"`
	RearRight     float64                `protobuf:"fixed64,4,opt,name=rear_right,json=rearRight,proto3" json:"rear_right,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerWeightProto) Reset() {
	*x = ContainerWeightProto{}
	mi := &file_api_proto_agv_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerWeightProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerWeightProto) ProtoMessage() {}

func (x *ContainerWeightProto) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agv_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerWeightProto.ProtoReflect.Descriptor instead.
func (*ContainerWeightProto) Descriptor() ([]byte, []int) {
	return file_api_proto_agv_proto_rawDescGZIP(), []int{1}
}

func (x *ContainerWeightProto) GetFrontLeft() float64 {
	if x != nil {
		return x.FrontLeft
	}
	return 0
}

func (x *ContainerWeightProto) GetFrontRight() float64 {
	if x != nil {
		return x.FrontRight
	}
	return 0
}

func (x *ContainerWeightProto) GetRearLeft() float64 {
	if x != nil {
		return x.RearLeft
	}
	return 0
}

func (x *ContainerWeightProto) GetRearRight() float64 {
	if x != nil {
		return x.RearRight
	}
	return 0
}

type DispatchTaskResponse struct {
	state               protoimpl.MessageState    `protogen:"open.v1"`
	Success             bool                      `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message             string                    `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	RouteId             string                    `protobuf:"bytes,3,opt,name=route_id,json=routeId,proto3" json:"route_id,omitempty"`
	Frames              []*ControlFrameProto      `protobuf:"bytes,4,rep,name=frames,proto3" json:"frames,omitempty"`
	TotalDistance       float64                   `protobuf:"fixed64,5,opt,name=total_distance,json=totalDistance,proto3" json:"total_distance,omitempty"`
	EstimatedTime       float64                   `protobuf:"fixed64,6,opt,name=estimated_time,json=estimatedTime,proto3" json:"estimated_time,omitempty"`
	KinematicAssessment *KinematicAssessmentProto `protobuf:"bytes,7,opt,name=kinematic_assessment,json=kinematicAssessment,proto3" json:"kinematic_assessment,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *DispatchTaskResponse) Reset() {
	*x = DispatchTaskResponse{}
	mi := &file_api_proto_agv_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispatchTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchTaskResponse) ProtoMessage() {}

func (x *DispatchTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agv_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchTaskResponse.ProtoReflect.Descriptor instead.
func (*DispatchTaskResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_agv_proto_rawDescGZIP(), []int{2}
}

func (x *DispatchTaskResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DispatchTaskResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DispatchTaskResponse) GetRouteId() string {
	if x != nil {
		return x.RouteId
	}
	return ""
}

func (x *DispatchTaskResponse) GetFrames() []*ControlFrameProto {
	if x != nil {
		return x.Frames
	}
	return nil
}

func (x *DispatchTaskResponse) GetTotalDistance() float64 {
	if x != nil {
		return x.TotalDistance
	}
	return 0
}

func (x *DispatchTaskResponse) GetEstimatedTime() float64 {
	if x != nil {
		return x.EstimatedTime
	}
	return 0
}

func (x *DispatchTaskResponse) GetKinematicAssessment() *KinematicAssessmentProto {
	if x != nil {
		return x.KinematicAssessment
	}
	return nil
}

type KinematicAssessmentProto struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	IsDegraded           bool                   `protobuf:"varint,1,opt,name=is_degraded,json=isDegraded,proto3" json:"is_degraded,omitempty"`
	Eccentricity         float64                `protobuf:"fixed64,2,opt,name=eccentricity,proto3" json:"eccentricity,omitempty"`
	Direction            string                 `protobuf:"bytes,3,opt,name=direction,proto3" json:"direction,omitempty"`
	SpeedReductionFactor float64                `protobuf:"fixed64,4,opt,name=speed_reduction_factor,json=speedReductionFactor,proto3" json:"speed_reduction_factor,omitempty"`
	MaxStraightSpeed     float64                `protobuf:"fixed64,5,opt,name=max_straight_speed,json=maxStraightSpeed,proto3" json:"max_straight_speed,omitempty"`
	MaxTurnSpeed         float64                `protobuf:"fixed64,6,opt,name=max_turn_speed,json=maxTurnSpeed,proto3" json:"max_turn_speed,omitempty"`
	RiskLevel            string                 `protobuf:"bytes,7,opt,name=risk_level,json=riskLevel,proto3" json:"risk_level,omitempty"`
	Reason               string                 `protobuf:"bytes,8,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *KinematicAssessmentProto) Reset() {
	*x = KinematicAssessmentProto{}
	mi := &file_api_proto_agv_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KinematicAssessmentProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KinematicAssessmentProto) ProtoMessage() {}

func (x *KinematicAssessmentProto) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agv_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KinematicAssessmentProto.ProtoReflect.Descriptor instead.
func (*KinematicAssessmentProto) Descriptor() ([]byte, []int) {
	return file_api_proto_agv_proto_rawDescGZIP(), []int{3}
}

func (x *KinematicAssessmentProto) GetIsDegraded() bool {
	if x != nil {
		return x.IsDegraded
	}
	return false
}

func (x *KinematicAssessmentProto) GetEccentricity() float64 {
	if x != nil {
		return x.Eccentricity
	}
	return 0
}

func (x *KinematicAssessmentProto) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *KinematicAssessmentProto) GetSpeedReductionFactor() float64 {
	if x != nil {
		return x.SpeedReductionFactor
	}
	return 0
}

func (x *KinematicAssessmentProto) GetMaxStraightSpeed() float64 {
	if x != nil {
		return x.MaxStraightSpeed
	}
	return 0
}

func (x *KinematicAssessmentProto) GetMaxTurnSpeed() float64 {
	if x != nil {
		return x.MaxTurnSpeed
	}
	return 0
}

func (x *KinematicAssessmentProto) GetRiskLevel() string {
	if x != nil {
		return x.RiskLevel
	}
	return ""
}

func (x *KinematicAssessmentProto) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ControlFrameProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sequence      int32                  `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Maneuver      int32                  `protobuf:"varint,3,opt,name=maneuver,proto3" json:"maneuver,omitempty"`
	Speed         float64                `protobuf:"fixed64,4,opt,name=speed,proto3" json:"speed,omitempty"`
	TargetAngle   float64                `protobuf:"fixed64,5,opt,name=target_angle,json=targetAngle,proto3" json:"target_angle,omitempty"`
	DeltaAngle    float64                `protobuf:"fixed64,6,opt,name=delta_angle,json=deltaAngle,proto3" json:"delta_angle,omitempty"`
	Distance      float64                `protobuf:"fixed64,7,opt,name=distance,proto3" json:"distance,omitempty"`
	AgvId         string                 `protobuf:"bytes,8,opt,name=agv_id,json=agvId,proto3" json:"agv_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlFrameProto) Reset() {
	*x = ControlFrameProto{}
	mi := &file_api_proto_agv_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlFrameProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlFrameProto) ProtoMessage() {}

func (x *ControlFrameProto) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agv_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlFrameProto.ProtoReflect.Descriptor instead.
func (*ControlFrameProto) Descriptor() ([]byte, []int) {
	return file_api_proto_agv_proto_rawDescGZIP(), []int{4}
}

func (x *ControlFrameProto) GetSequence() int32 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *ControlFrameProto) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ControlFrameProto) GetManeuver() int32 {
	if x != nil {
		return x.Maneuver
	}
	return 0
}

func (x *ControlFrameProto) GetSpeed() float64 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *ControlFrameProto) GetTargetAngle() float64 {
	if x != nil {
		return x.TargetAngle
	}
	return 0
}

func (x *ControlFrameProto) GetDeltaAngle() float64 {
	if x != nil {
		return x.DeltaAngle
	}
	return 0
}

func (x *ControlFrameProto) GetDistance() float64 {
	if x != nil {
		return x.Distance
	}
	return 0
}

func (x *ControlFrameProto) GetAgvId() string {
	if x != nil {
		return x.AgvId
	}
	return ""
}

type StreamTaskStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamTaskStatusRequest) Reset() {
	*x = StreamTaskStatusRequest{}
	mi := &file_api_proto_agv_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamTaskStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamTaskStatusRequest) ProtoMessage() {}

func (x *StreamTaskStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agv_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamTaskStatusRequest.ProtoReflect.Descriptor instead.
func (*StreamTaskStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_agv_proto_rawDescGZIP(), []int{5}
}

func (x *StreamTaskStatusRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type TaskStatusUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	AgvId         string                 `protobuf:"bytes,2,opt,name=agv_id,json=agvId,proto3" json:"agv_id,omitempty"`
	Status        int32                  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	CurrentNodeId string                 `protobuf:"bytes,4,opt,name=current_node_id,json=currentNodeId,proto3" json:"current_node_id,omitempty"`
	Progress      float64                `protobuf:"fixed64,5,opt,name=progress,proto3" json:"progress,omitempty"`
	Timestamp     int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskStatusUpdate) Reset() {
	*x = TaskStatusUpdate{}
	mi := &file_api_proto_agv_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskStatusUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskStatusUpdate) ProtoMessage() {}

func (x *TaskStatusUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agv_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskStatusUpdate.ProtoReflect.Descriptor instead.
func (*TaskStatusUpdate) Descriptor() ([]byte, []int) {
	return file_api_proto_agv_proto_rawDescGZIP(), []int{6}
}

func (x *TaskStatusUpdate) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskStatusUpdate) GetAgvId() string {
	if x != nil {
		return x.AgvId
	}
	return ""
}

func (x *TaskStatusUpdate) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *TaskStatusUpdate) GetCurrentNodeId() string {
	if x != nil {
		return x.CurrentNodeId
	}
	return ""
}

func (x *TaskStatusUpdate) GetProgress() float64 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *TaskStatusUpdate) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type GetRouteRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	SourceNodeId        string                 `protobuf:"bytes,1,opt,name=source_node_id,json=sourceNodeId,proto3" json:"source_node_id,omitempty"`
	TargetNodeId        string                 `protobuf:"bytes,2,opt,name=target_node_id,json=targetNodeId,proto3" json:"target_node_id,omitempty"`
	IntermediateNodeIds []string               `protobuf:"bytes,3,rep,name=intermediate_node_ids,json=intermediateNodeIds,proto3" json:"intermediate_node_ids,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetRouteRequest) Reset() {
	*x = GetRouteRequest{}
	mi := &file_api_proto_agv_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRouteRequest) ProtoMessage() {}

func (x *GetRouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agv_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRouteRequest.ProtoReflect.Descriptor instead.
func (*GetRouteRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_agv_proto_rawDescGZIP(), []int{7}
}

func (x *GetRouteRequest) GetSourceNodeId() string {
	if x != nil {
		return x.SourceNodeId
	}
	return ""
}

func (x *GetRouteRequest) GetTargetNodeId() string {
	if x != nil {
		return x.TargetNodeId
	}
	return ""
}

func (x *GetRouteRequest) GetIntermediateNodeIds() []string {
	if x != nil {
		return x.IntermediateNodeIds
	}
	return nil
}

type GetRouteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Path          []*PathNodeProto       `protobuf:"bytes,2,rep,name=path,proto3" json:"path,omitempty"`
	TotalDistance float64                `protobuf:"fixed64,3,opt,name=total_distance,json=totalDistance,proto3" json:"total_distance,omitempty"`
	TotalWeight   float64                `protobuf:"fixed64,4,opt,name=total_weight,json=totalWeight,proto3" json:"total_weight,omitempty"`
	Edges         []*EdgeInfoProto       `protobuf:"bytes,5,rep,name=edges,proto3" json:"edges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRouteResponse) Reset() {
	*x = GetRouteResponse{}
	mi := &file_api_proto_agv_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRouteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRouteResponse) ProtoMessage() {}

func (x *GetRouteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agv_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRouteResponse.ProtoReflect.Descriptor instead.
func (*GetRouteResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_agv_proto_rawDescGZIP(), []int{8}
}

func (x *GetRouteResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetRouteResponse) GetPath() []*PathNodeProto {
	if x != nil {
		return x.Path
	}
	return nil
}

func (x *GetRouteResponse) GetTotalDistance() float64 {
	if x != nil {
		return x.TotalDistance
	}
	return 0
}

func (x *GetRouteResponse) GetTotalWeight() float64 {
	if x != nil {
		return x.TotalWeight
	}
	return 0
}

func (x *GetRouteResponse) GetEdges() []*EdgeInfoProto {
	if x != nil {
		return x.Edges
	}
	return nil
}

type PathNodeProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	X             float64                `protobuf:"fixed64,2,opt,name=x,proto3" json:"x,omitempty"`
	Y             float64                `protobuf:"fixed64,3,opt,name=y,proto3" json:"y,omitempty"`
	Angle         float64                `protobuf:"fixed64,4,opt,name=angle,proto3" json:"angle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PathNodeProto) Reset() {
	*x = PathNodeProto{}
	mi := &file_api_proto_agv_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PathNodeProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PathNodeProto) ProtoMessage() {}

func (x *PathNodeProto) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agv_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PathNodeProto.ProtoReflect.Descriptor instead.
func (*PathNodeProto) Descriptor() ([]byte, []int) {
	return file_api_proto_agv_proto_rawDescGZIP(), []int{9}
}

func (x *PathNodeProto) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PathNodeProto) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *PathNodeProto) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *PathNodeProto) GetAngle() float64 {
	if x != nil {
		return x.Angle
	}
	return 0
}

type EdgeInfoProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Weight        float64                `protobuf:"fixed64,3,opt,name=weight,proto3" json:"weight,omitempty"`
	Length        float64                `protobuf:"fixed64,4,opt,name=length,proto3" json:"length,omitempty"`
	Congestion    float64                `protobuf:"fixed64,5,opt,name=congestion,proto3" json:"congestion,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EdgeInfoProto) Reset() {
	*x = EdgeInfoProto{}
	mi := &file_api_proto_agv_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EdgeInfoProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EdgeInfoProto) ProtoMessage() {}

func (x *EdgeInfoProto) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agv_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EdgeInfoProto.ProtoReflect.Descriptor instead.
func (*EdgeInfoProto) Descriptor() ([]byte, []int) {
	return file_api_proto_agv_proto_rawDescGZIP(), []int{10}
}

func (x *EdgeInfoProto) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *EdgeInfoProto) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *EdgeInfoProto) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *EdgeInfoProto) GetLength() float64 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *EdgeInfoProto) GetCongestion() float64 {
	if x != nil {
		return x.Congestion
	}
	return 0
}

var File_api_proto_agv_proto protoreflect.FileDescriptor

const file_api_proto_agv_proto_rawDesc = "" +
	"\n" +
	"\x13api/proto/agv.proto\x12\x03agv\"\xbb\x02\n" +
	"\x13DispatchTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12!\n" +
	"\fcontainer_id\x18\x02 \x01(\tR\vcontainerId\x12\x15\n" +
	"\x06agv_id\x18\x03 \x01(\tR\x05agvId\x12 \n" +
	"\fyard_node_id\x18\x04 \x01(\tR\n" +
	"yardNodeId\x12(\n" +
	"\x10quayside_node_id\x18\x05 \x01(\tR\x0equaysideNodeId\x12\x1a\n" +
	"\bpriority\x18\x06 \x01(\x05R\bpriority\x12#\n" +
	"\rdeadline_unix\x18\a \x01(\x03R\fdeadlineUnix\x12D\n" +
	"\x10container_weight\x18\b \x01(\v2\x19.agv.ContainerWeightProtoR\x0fcontainerWeight\"\x92\x01\n" +
	"\x14ContainerWeightProto\x12\x1d\n" +
	"\n" +
	"front_left\x18\x01 \x01(\x01R\tfrontLeft\x12\x1f\n" +
	"\vfront_right\x18\x02 \x01(\x01R\n" +
	"frontRight\x12\x1b\n" +
	"\trear_left\x18\x03 \x01(\x01R\brearLeft\x12\x1d\n" +
	"\n" +
	"rear_right\x18\x04 \x01(\x01R\trearRight\"\xb5\x02\n" +
	"\x14DispatchTaskResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x19\n" +
	"\broute_id\x18\x03 \x01(\tR\arouteId\x12.\n" +
	"\x06frames\x18\x04 \x03(\v2\x16.agv.ControlFrameProtoR\x06frames\x12%\n" +
	"\x0etotal_distance\x18\x05 \x01(\x01R\rtotalDistance\x12%\n" +
	"\x0eestimated_time\x18\x06 \x01(\x01R\restimatedTime\x12P\n" +
	"\x14kinematic_assessment\x18\a \x01(\v2\x1d.agv.KinematicAssessmentProtoR\x13kinematicAssessment\"\xbe\x02\n" +
	"\x18KinematicAssessmentProto\x12\x1f\n" +
	"\vis_degraded\x18\x01 \x01(\bR\n" +
	"isDegraded\x12\"\n" +
	"\feccentricity\x18\x02 \x01(\x01R\feccentricity\x12\x1c\n" +
	"\tdirection\x18\x03 \x01(\tR\tdirection\x124\n" +
	"\x16speed_reduction_factor\x18\x04 \x01(\x01R\x14speedReductionFactor\x12,\n" +
	"\x12max_straight_speed\x18\x05 \x01(\x01R\x10maxStraightSpeed\x12$\n" +
	"\x0emax_turn_speed\x18\x06 \x01(\x01R\fmaxTurnSpeed\x12\x1d\n" +
	"\n" +
	"risk_level\x18\a \x01(\tR\triskLevel\x12\x16\n" +
	"\x06reason\x18\b \x01(\tR\x06reason\"\xf1\x01\n" +
	"\x11ControlFrameProto\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x05R\bsequence\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x1a\n" +
	"\bmaneuver\x18\x03 \x01(\x05R\bmaneuver\x12\x14\n" +
	"\x05speed\x18\x04 \x01(\x01R\x05speed\x12!\n" +
	"\ftarget_angle\x18\x05 \x01(\x01R\vtargetAngle\x12\x1f\n" +
	"\vdelta_angle\x18\x06 \x01(\x01R\n" +
	"deltaAngle\x12\x1a\n" +
	"\bdistance\x18\a \x01(\x01R\bdistance\x12\x15\n" +
	"\x06agv_id\x18\b \x01(\tR\x05agvId\"2\n" +
	"\x17StreamTaskStatusRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"\xbc\x01\n" +
	"\x10TaskStatusUpdate\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x15\n" +
	"\x06agv_id\x18\x02 \x01(\tR\x05agvId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status\x12&\n" +
	"\x0fcurrent_node_id\x18\x04 \x01(\tR\rcurrentNodeId\x12\x1a\n" +
	"\bprogress\x18\x05 \x01(\x01R\bprogress\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\"\x91\x01\n" +
	"\x0fGetRouteRequest\x12$\n" +
	"\x0esource_node_id\x18\x01 \x01(\tR\fsourceNodeId\x12$\n" +
	"\x0etarget_node_id\x18\x02 \x01(\tR\ftargetNodeId\x122\n" +
	"\x15intermediate_node_ids\x18\x03 \x03(\tR\x13intermediateNodeIds\"\xc4\x01\n" +
	"\x10GetRouteResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12&\n" +
	"\x04path\x18\x02 \x03(\v2\x12.agv.PathNodeProtoR\x04path\x12%\n" +
	"\x0etotal_distance\x18\x03 \x01(\x01R\rtotalDistance\x12!\n" +
	"\ftotal_weight\x18\x04 \x01(\x01R\vtotalWeight\x12(\n" +
	"\x05edges\x18\x05 \x03(\v2\x12.agv.EdgeInfoProtoR\x05edges\"Q\n" +
	"\rPathNodeProto\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\f\n" +
	"\x01x\x18\x02 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x01R\x01y\x12\x14\n" +
	"\x05angle\x18\x04 \x01(\x01R\x05angle\"\x83\x01\n" +
	"\rEdgeInfoProto\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\tR\x02to\x12\x16\n" +
	"\x06weight\x18\x03 \x01(\x01R\x06weight\x12\x16\n" +
	"\x06length\x18\x04 \x01(\x01R\x06length\x12\x1e\n" +
	"\n" +
	"congestion\x18\x05 \x01(\x01R\n" +
	"congestion2\xdd\x01\n" +
	"\x12AGVDispatchService\x12C\n" +
	"\fDispatchTask\x12\x18.agv.DispatchTaskRequest\x1a\x19.agv.DispatchTaskResponse\x12I\n" +
	"\x10StreamTaskStatus\x12\x1c.agv.StreamTaskStatusRequest\x1a\x15.agv.TaskStatusUpdate0\x01\x127\n" +
	"\bGetRoute\x12\x14.agv.GetRouteRequest\x1a\x15.agv.GetRouteResponseB+Z)github.com/port-agv/routing/api/proto/agvb\x06proto3"

var (
	file_api_proto_agv_proto_rawDescOnce sync.Once
	file_api_proto_agv_proto_rawDescData []byte
)

func file_api_proto_agv_proto_rawDescGZIP() []byte {
	file_api_proto_agv_proto_rawDescOnce.Do(func() {
		file_api_proto_agv_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_agv_proto_rawDesc), len(file_api_proto_agv_proto_rawDesc)))
	})
	return file_api_proto_agv_proto_rawDescData
}

var file_api_proto_agv_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_proto_agv_proto_goTypes = []any{
	(*DispatchTaskRequest)(nil),      // 0: agv.DispatchTaskRequest
	(*ContainerWeightProto)(nil),     // 1: agv.ContainerWeightProto
	(*DispatchTaskResponse)(nil),     // 2: agv.DispatchTaskResponse
	(*KinematicAssessmentProto)(nil), // 3: agv.KinematicAssessmentProto
	(*ControlFrameProto)(nil),        // 4: agv.ControlFrameProto
	(*StreamTaskStatusRequest)(nil),  // 5: agv.StreamTaskStatusRequest
	(*TaskStatusUpdate)(nil),         // 6: agv.TaskStatusUpdate
	(*GetRouteRequest)(nil),          // 7: agv.GetRouteRequest
	(*GetRouteResponse)(nil),         // 8: agv.GetRouteResponse
	(*PathNodeProto)(nil),            // 9: agv.PathNodeProto
	(*EdgeInfoProto)(nil),            // 10: agv.EdgeInfoProto
}
var file_api_proto_agv_proto_depIdxs = []int32{
	1,  // 0: agv.DispatchTaskRequest.container_weight:type_name -> agv.ContainerWeightProto
	4,  // 1: agv.DispatchTaskResponse.frames:type_name -> agv.ControlFrameProto
	3,  // 2: agv.DispatchTaskResponse.kinematic_assessment:type_name -> agv.KinematicAssessmentProto
	9,  // 3: agv.GetRouteResponse.path:type_name -> agv.PathNodeProto
	10, // 4: agv.GetRouteResponse.edges:type_name -> agv.EdgeInfoProto
	0,  // 5: agv.AGVDispatchService.DispatchTask:input_type -> agv.DispatchTaskRequest
	5,  // 6: agv.AGVDispatchService.StreamTaskStatus:input_type -> agv.StreamTaskStatusRequest
	7,  // 7: agv.AGVDispatchService.GetRoute:input_type -> agv.GetRouteRequest
	2,  // 8: agv.AGVDispatchService.DispatchTask:output_type -> agv.DispatchTaskResponse
	6,  // 9: agv.AGVDispatchService.StreamTaskStatus:output_type -> agv.TaskStatusUpdate
	8,  // 10: agv.AGVDispatchService.GetRoute:output_type -> agv.GetRouteResponse
	8,  // [8:11] is the sub-list for method output_type
	5,  // [5:8] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_api_proto_agv_proto_init() }
func file_api_proto_agv_proto_init() {
	if File_api_proto_agv_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_agv_proto_rawDesc), len(file_api_proto_agv_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_agv_proto_goTypes,
		DependencyIndexes: file_api_proto_agv_proto_depIdxs,
		MessageInfos:      file_api_proto_agv_proto_msgTypes,
	}.Build()
	File_api_proto_agv_proto = out.File
	file_api_proto_agv_proto_goTypes = nil
	file_api_proto_agv_proto_depIdxs = nil
}
