// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.28.3
// source: api/proto/agv.proto

package agv

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AGVDispatchService_DispatchTask_FullMethodName     = "/agv.AGVDispatchService/DispatchTask"
	AGVDispatchService_StreamTaskStatus_FullMethodName = "/agv.AGVDispatchService/StreamTaskStatus"
	AGVDispatchService_GetRoute_FullMethodName         = "/agv.AGVDispatchService/GetRoute"
)

// AGVDispatchServiceClient is the client API for AGVDispatchService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AGVDispatchServiceClient interface {
	DispatchTask(ctx context.Context, in *DispatchTaskRequest, opts ...grpc.CallOption) (*DispatchTaskResponse, error)
	StreamTaskStatus(ctx context.Context, in *StreamTaskStatusRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TaskStatusUpdate], error)
	GetRoute(ctx context.Context, in *GetRouteRequest, opts ...grpc.CallOption) (*GetRouteResponse, error)
}

type aGVDispatchServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAGVDispatchServiceClient(cc grpc.ClientConnInterface) AGVDispatchServiceClient {
	return &aGVDispatchServiceClient{cc}
}

func (c *aGVDispatchServiceClient) DispatchTask(ctx context.Context, in *DispatchTaskRequest, opts ...grpc.CallOption) (*DispatchTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DispatchTaskResponse)
	err := c.cc.Invoke(ctx, AGVDispatchService_DispatchTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aGVDispatchServiceClient) StreamTaskStatus(ctx context.Context, in *StreamTaskStatusRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TaskStatusUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AGVDispatchService_ServiceDesc.Streams[0], AGVDispatchService_StreamTaskStatus_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamTaskStatusRequest, TaskStatusUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AGVDispatchService_StreamTaskStatusClient = grpc.ServerStreamingClient[TaskStatusUpdate]

func (c *aGVDispatchServiceClient) GetRoute(ctx context.Context, in *GetRouteRequest, opts ...grpc.CallOption) (*GetRouteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRouteResponse)
	err := c.cc.Invoke(ctx, AGVDispatchService_GetRoute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AGVDispatchServiceServer is the server API for AGVDispatchService service.
// All implementations must embed UnimplementedAGVDispatchServiceServer
// for forward compatibility.
type AGVDispatchServiceServer interface {
	DispatchTask(context.Context, *DispatchTaskRequest) (*DispatchTaskResponse, error)
	StreamTaskStatus(*StreamTaskStatusRequest, grpc.ServerStreamingServer[TaskStatusUpdate]) error
	GetRoute(context.Context, *GetRouteRequest) (*GetRouteResponse, error)
	mustEmbedUnimplementedAGVDispatchServiceServer()
}

// UnimplementedAGVDispatchServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAGVDispatchServiceServer struct{}

func (UnimplementedAGVDispatchServiceServer) DispatchTask(context.Context, *DispatchTaskRequest) (*DispatchTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DispatchTask not implemented")
}
func (UnimplementedAGVDispatchServiceServer) StreamTaskStatus(*StreamTaskStatusRequest, grpc.ServerStreamingServer[TaskStatusUpdate]) error {
	return status.Error(codes.Unimplemented, "method StreamTaskStatus not implemented")
}
func (UnimplementedAGVDispatchServiceServer) GetRoute(context.Context, *GetRouteRequest) (*GetRouteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRoute not implemented")
}
func (UnimplementedAGVDispatchServiceServer) mustEmbedUnimplementedAGVDispatchServiceServer() {}
func (UnimplementedAGVDispatchServiceServer) testEmbeddedByValue()                            {}

// UnsafeAGVDispatchServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AGVDispatchServiceServer will
// result in compilation errors.
type UnsafeAGVDispatchServiceServer interface {
	mustEmbedUnimplementedAGVDispatchServiceServer()
}

func RegisterAGVDispatchServiceServer(s grpc.ServiceRegistrar, srv AGVDispatchServiceServer) {
	// If the following call panics, it indicates UnimplementedAGVDispatchServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AGVDispatchService_ServiceDesc, srv)
}

func _AGVDispatchService_DispatchTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DispatchTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AGVDispatchServiceServer).DispatchTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AGVDispatchService_DispatchTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AGVDispatchServiceServer).DispatchTask(ctx, req.(*DispatchTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AGVDispatchService_StreamTaskStatus_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamTaskStatusRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AGVDispatchServiceServer).StreamTaskStatus(m, &grpc.GenericServerStream[StreamTaskStatusRequest, TaskStatusUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AGVDispatchService_StreamTaskStatusServer = grpc.ServerStreamingServer[TaskStatusUpdate]

func _AGVDispatchService_GetRoute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRouteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AGVDispatchServiceServer).GetRoute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AGVDispatchService_GetRoute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AGVDispatchServiceServer).GetRoute(ctx, req.(*GetRouteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AGVDispatchService_ServiceDesc is the grpc.ServiceDesc for AGVDispatchService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AGVDispatchService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agv.AGVDispatchService",
	HandlerType: (*AGVDispatchServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DispatchTask",
			Handler:    _AGVDispatchService_DispatchTask_Handler,
		},
		{
			MethodName: "GetRoute",
			Handler:    _AGVDispatchService_GetRoute_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamTaskStatus",
			Handler:       _AGVDispatchService_StreamTaskStatus_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/proto/agv.proto",
}
